# Generated by Django 3.1.3 on 2020-12-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_created=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('srp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('margin', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
