# Generated by Django 3.1.3 on 2021-03-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('barcode_number', models.CharField(blank=True, max_length=13)),
                ('enable', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('srp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('packing', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('posting_datetime', models.DateTimeField(blank=True)),
                ('purchase_order_number', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('supplier', models.CharField(blank=True, default=None, max_length=100)),
                ('status', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(max_length=100)),
                ('status', models.CharField(default='None', max_length=100)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modifeid', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.purchaseorder')),
            ],
        ),
    ]
