# Generated by Django 3.1.3 on 2021-03-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.CharField(blank=True, default=None, max_length=255, primary_key=True, serialize=False),
        ),
    ]
