# Generated by Django 3.1.3 on 2021-04-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20210328_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereceipt',
            old_name='purchase_order',
            new_name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='id',
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='purchase_receipt_number',
            field=models.CharField(blank=True, default=None, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_receipt_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.purchasereceipt')),
            ],
        ),
    ]
