# Generated by Django 3.1.3 on 2020-12-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20201218_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-modified']},
        ),
    ]
