# Generated by Django 3.1.3 on 2021-04-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20210415_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='sales_invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salesinvoice'),
        ),
    ]
