# Generated by Django 3.1.3 on 2021-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20210408_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
