# Generated by Django 3.1.3 on 2021-04-08 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_purchasereceipt_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='posting_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
