# Generated by Django 3.1.3 on 2021-01-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='sku',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pos.item'),
        ),
    ]
