# Generated by Django 3.1.3 on 2021-04-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_purchasereceipt_posting_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['-modified']},
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='modifeid',
            new_name='modified',
        ),
    ]
