# Generated by Django 3.1.3 on 2021-04-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20210409_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
