# Generated by Django 3.1.3 on 2021-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20210305_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
