# Generated by Django 3.1.3 on 2021-04-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20210410_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
