# Generated by Django 3.1.3 on 2021-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_item_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
