# Generated by Django 3.1.3 on 2021-03-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20210305_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='posting_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
