# Generated by Django 3.1.3 on 2021-03-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20210306_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[(1, 'Draft'), (2, 'Complete'), (3, 'Cancelled')], default='draft', max_length=10),
        ),
    ]
