# Generated by Django 3.1.3 on 2021-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20210306_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
