# Generated by Django 3.1.3 on 2021-03-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20210306_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
