# Generated by Django 3.1.3 on 2021-04-12 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='purchase_order_number',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='pos.purchaseorder'),
            preserve_default=False,
        ),
    ]
