# Generated by Django 3.1.3 on 2021-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20210307_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
