# Generated by Django 3.1.3 on 2021-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_purchasereceiptitem_purchase_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
