# Generated by Django 3.1.3 on 2021-03-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
