# Generated by Django 3.1.3 on 2021-04-13 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_purchaseorder_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='posting_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
