# Generated by Django 3.1.3 on 2021-04-13 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_purchaseorder_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='itemid',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='pos.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='posting_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
