# Generated by Django 3.1.3 on 2021-04-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_stocktransaction_posting_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='packing',
        ),
    ]
