# Generated by Django 3.1.3 on 2021-03-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20210309_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='sku',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='price',
            new_name='total',
        ),
    ]
