# Generated by Django 3.1.3 on 2021-04-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_remove_item_packing'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='item_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pos.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='voucher_no',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
