# Generated by Django 3.1.3 on 2021-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20210310_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='key',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
