# Generated by Django 3.1.3 on 2021-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_purchaseorderitem_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='posting_datetime',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='key',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
