# Generated by Django 3.1.3 on 2021-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_auto_20210413_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='posting_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
