# Generated by Django 3.1.3 on 2021-04-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20210413_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='pos.item'),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='item_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='pos.item'),
        ),
    ]
