# Generated by Django 3.1.3 on 2021-03-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20210311_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_id',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
