# Generated by Django 3.1.3 on 2021-04-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20210413_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchasereceiptitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='item_id',
            new_name='item',
        ),
    ]
