# Generated by Django 3.1.3 on 2021-03-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_purchaseorderitem_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item_id',
        ),
    ]
