# Generated by Django 3.1.3 on 2021-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20210413_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
