# Generated by Django 3.1.3 on 2021-03-11 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_remove_purchaseorderitem_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='total',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='posting_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
