# Generated by Django 3.1.3 on 2021-03-11 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_auto_20210311_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='posting_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
