# Generated by Django 3.1.3 on 2021-04-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_auto_20210413_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='voucher_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
