# Generated by Django 3.1.3 on 2021-03-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_item_posting_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='qty',
            field=models.CharField(max_length=100),
        ),
    ]
