# Generated by Django 3.1.3 on 2021-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_auto_20210311_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
