# Generated by Django 3.1.3 on 2021-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_auto_20210311_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='key',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
