# Generated by Django 3.1.3 on 2021-03-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_auto_20210311_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
