# Generated by Django 3.1.3 on 2021-03-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_auto_20210311_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='key',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.purchaseorder'),
        ),
    ]
