# Generated by Django 3.1.3 on 2021-03-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_auto_20210311_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total',
        ),
    ]
