# Generated by Django 3.1.3 on 2021-03-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_remove_purchaseorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='key',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='total',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
