# Generated by Django 3.1.3 on 2021-03-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_auto_20210312_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='posting_datetime',
        ),
    ]
