# Generated by Django 3.1.3 on 2021-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_remove_item_posting_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enable',
            field=models.BooleanField(default=1),
        ),
    ]
