# Generated by Django 3.1.3 on 2021-03-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_item_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='margin',
            new_name='packing',
        ),
    ]
